version: 2.1

jobs:
  test:
    working_directory: ~/refinery

    docker:
      - image: cimg/openjdk:11.0.12

    steps:
      - checkout
      - run:
          name: Build and deploy the artifact
          command: ./gradlew build
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/refinery/build/reports
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  publish:
    docker:
      - image: cimg/openjdk:11.0.12
    
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Build and deploy the artifact
          command: ./gradlew publish -Pversion=${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}


workflows:
  version: 2
  workflow:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
              ignore: /pull\/[0-9]+/
