version: 2.1

jobs:
  build:
    working_directory: ~/refinery

    docker:
      - image: cimg/openjdk:11.0.12

    steps:
      - checkout
      - run:
          name: Build and deploy the artifact
          command: ./gradlew build publish -Pversion=${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/build/reports

workflows:
  version: 2
  workflow:
    jobs:
      - build
